//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE.Mvc.Samples.ViewEngine.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVE.Mvc.Samples.ViewEngine.L10N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Start Bootstrap:.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death to the Stock Photo:
        ///Special Thanks.
        /// </summary>
        internal static string Content1Head {
            get {
                return ResourceManager.GetString("Content1Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special thanks to Death to the Stock Photo for providing the photographs that you see in this template. Visit their website to become a member..
        /// </summary>
        internal static string Content1Lead {
            get {
                return ResourceManager.GetString("Content1Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Device Mockups
        ///by PSDCovers.
        /// </summary>
        internal static string Content2Head {
            get {
                return ResourceManager.GetString("Content2Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by PSDCovers! Visit their website to download some of their awesome, free photoshop actions!.
        /// </summary>
        internal static string Content2Lead {
            get {
                return ResourceManager.GetString("Content2Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Web Fonts and
        ///Font Awesome Icons.
        /// </summary>
        internal static string Content3Head {
            get {
                return ResourceManager.GetString("Content3Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template features the &apos;Lato&apos; font, part of the Google Web Font library, as well as icons from Font Awesome..
        /// </summary>
        internal static string Content3Lead {
            get {
                return ResourceManager.GetString("Content3Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Landing Page -----.
        /// </summary>
        internal static string Head1 {
            get {
                return ResourceManager.GetString("Head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Template by Start Bootstrap.
        /// </summary>
        internal static string Head2 {
            get {
                return ResourceManager.GetString("Head2", resourceCulture);
            }
        }
    }
}
